version: '3.5'

services:

  portainer:    
    image: portainer/portainer    
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - network1
    restart: unless-stopped
  
  postgres:
    image: postgres
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p@ssw0rd1}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - network1
    restart: unless-stopped

  pgadmin:    
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - network1
    restart: unless-stopped

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      - network1

networks:
  network1:
    driver: bridge

volumes:
  portainer:
  postgres:
  pgadmin:
  mysql:
  mysql_config: