start:
	docker-compose up -d

portainer:
	docker-compose up -d portainer

mysql:
	docker-compose up -d mysql

postgres:
	docker-compose up -d postgres

pgadmin:
	docker-compose up -d pgadmin

pg:
	docker-compose up -d postgres pgadmin

stop:
	docker-compose down